apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-py-deployment
  labels:
    app: rt-py-deployment
spec:
  selector:
    matchLabels:
      app: rt-py-deployment
  template:
    metadata:
      labels:
        app: rt-py-deployment
    spec:
      containers:
        - name: rt-py-deployment
          image: shehzadmohammed/review_trackers_project:main
          ports:
            - containerPort: 8090
          resources:
            limits:
              cpu: 500m
              memory: "1000Mi"
            requests:
              cpu: 100m
              memory: "500Mi"
