apiVersion: v1
kind: Service
metadata:
  name: rt-py-service
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: rt-py-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30201
  type: LoadBalancer
