apiVersion: v1
kind: Service
metadata:
  name: rt-py-service
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: rt-py-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 20010
      nodePort: 30201
  type: LoadBalancer
