name: Continuous Deployment
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Terraform-Infrastructure/**.tf'
      - 'Kubernetes/**'

    workflow_dispatch:
    jobs: 
      Continous_Deployment:
        steps: 
          - name: Checkout
            uses: actions/checkout@v3


