name: Continuous Deployment
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Terraform-Infrastructure/**.tf'
      - 'Kubernetes/**'

    workflow_dispatch:

jobs: 
  Test:

    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Intializes Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Get Storage Account Name
        id: storageaccname
        run: cat Terraform-Infrastructure/storageaccname.txt

      - name: Terraform Intializes
        run: terraform init -backend-config="storage_account_name="${{ steps.storageaccname.outputs.* }}"" -backend-config="container_name="remotestatecontainer"" -backend-config="resource_group_name="rt-infra"" -backend-config="key="terraform.tfstate""
      
      - name: Terraform FMT
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan
      
  Deploy: 
    runs_on: ubuntu-latest
      
      - name: Terraform Apply
        run: terraform apply



