name: Docker Image CI - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "Python-Server/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Python-Server/**"

  workflow_dispatch:

jobs:
  Docker_Integeration:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.0

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: lint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Python-Server/Dockerfile

      - name: Docker Metadata
        id: data
        uses: docker/metadata-action@v4.1.0
        with:
          images: |
            shehzadmohammed/review_trackers_project
          tags: |
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        if: ${{ github.event_name == 'push' }}
        with:
          context: Python-Server
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.data.outputs.tags }}, shehzadmohammed/review_trackers_project:latest
          labels: ${{ steps.data.outputs.label}}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ github.event_name == 'push' }}
        with:
          image-ref: "docker.io/${{ steps.data.outputs.tags }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      
      - name: Dispatch Kubernetes Deployment
        uses: passeidireto/trigger-external-workflow-action@v1.0.0
        with:
          repository: ShehzadMohammed/Review-Trackers-Project
          event: docker_build
          github_pat: ${{ secrets.REPO_PAT }}
