name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Python-Server/**'
      - '.github/workflows/docker-workflow.yaml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'Python-Server/**'
      - '.github/workflows/docker-workflow.yaml'

  workflow_dispatch: 

jobs:
  Docker_Build_And_Push:
    
    runs-on: ubuntu-latest
    env: 
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Docker Metadata
        id: data
        uses: docker/metadata-action@v4.1.0
        with:
          images: |
            shehzadmohammed/review_trackers_project
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and Push 
        uses: docker/build-push-action@v3.2.0
        with: 
          context: Python-Server
          platforms: linux/amd64, linux/arm/v6  # Enabling mac users :)
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.data.outputs.tags }}
          labels: ${{ steps.data.outputs.label}}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/review_trackers_project:${{ steps.data.outputs.tags }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
