name: Terraform State Migration
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  Terraform-State-Migration:
    runs-on: ubuntu-latest
    env:
      AKS_CLUSTER_NAME: "rtpykube"
      RESOURCE_GROUP_NAME: "rt-infra"
      RESOURCE_GROUP_LOCATION: "East US"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Intializes Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Az login via cli
        if: always()
        run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: KeywordReplace For Terraform
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["Terraform-Infrastructure/variables.tf"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          AKS_CLUSTER_NAME: ${{ env.AKS_CLUSTER_NAME }}
          RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          RESOURCE_GROUP_LOCATION: ${{ env.RESOURCE_GROUP_LOCATION }}

      - name: Terraform Intializes
        shell: pwsh
        run: |
          cd Terraform-Infrastructure
          (Get-Content ./variables.tf).Replace('replace-variable', "${{ secrets.STORAGE_ACCOUNT_NAME }}") | Set-Content ./variables.tf
          terraform init terraform init -backend-config="storage_account_name=${{ secrets.INTIAL_STORAGE_ACCOUNT }}" -backend-config="access_key=${{ secrets.INTIAL_STORAGE_KEY }}"
          terraform init -migrate-state -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -backend-config="access_key=${{ secrets.STORAGE_ACCOUNT_KEY }}" -backend-config="container_name=remotestatecontainer" -backend-config="resource_group_name=rt-infra" -backend-config="key=terraform.tfstate"
          terraform plan 
          terraform apply --auto-approve
