name: Terraform Destroy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  Terraform_Destroy:
    runs-on: ubuntu-latest
    outputs:
      storageaccname: ${{ steps.storageaccname.outputs.strname }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Intializes Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4

      - name: Az login via cli
        if: always()
        run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Intializes
        run: |
          cd Terraform-Infrastructure
          terraform init -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -backend-config="access_key=${{ secrets.STORAGE_ACCOUNT_KEY }}" -backend-config="container_name=remotestatecontainer" -backend-config="resource_group_name=rt-infra" -backend-config="key=terraform.tfstate"

      - name: Terraform Destroy
        run: |
          cd Terraform-Infrastructure
          terraform destroy --auto-approve

