name: Terraform Deployment
on:
  push:
    branches: ["main"]
    paths:
      - "Terraform-Infrastructure/**.tf"
  pull_request:
    branches: ["main"]
    paths:
      - "Terraform-Infrastructure/**.tf"

  workflow_dispatch:

jobs:
  Terraform_Deployment:
    runs-on: ubuntu-latest
    env:
      AKS_CLUSTER_NAME: "rtpykube"
      RESOURCE_GROUP_NAME: "rt-infra"
      RESOURCE_GROUP_LOCATION: "East US"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    steps:
      - uses: ./.github/workflows/Intialization_Template

      - name: Terraform lint
        run: |
          cd Terraform-Infrastructure
          terraform fmt

      - name: Terraform Intializes
        shell: pwsh
        run: |
          cd Terraform-Infrastructure
          (Get-Content ./variables.tf).Replace('replace-variable', "${{ secrets.STORAGE_ACCOUNT_NAME }}") | Set-Content ./variables.tf
          terraform init -backend-config="access_key=${{ secrets.INTIAL_STORAGE_KEY }}"  -backend-config="storage_account_name=${{ secrets.INTIAL_STORAGE_ACCOUNT }}"

      - name: Terraform Validate
        run: |
          cd Terraform-Infrastructure
          terraform validate

      - name: Terraform Plan
        run: |
          cd Terraform-Infrastructure
          terraform plan -detailed-exitcode || res=$?
          if (($res == 0))
          then 
            exit 0;
          fi

      - name: Terraform Apply
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd Terraform-Infrastructure
          terraform apply --auto-approve
