name: Terraform Destroy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  Terraform_Destroy:
    runs-on: ubuntu-latest
    env:
      AKS_CLUSTER_NAME: "rtpykube"
      RESOURCE_GROUP_NAME: "rt-infra"
      RESOURCE_GROUP_LOCATION: "East US"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
    steps:
      - uses: ./.github/workflows/Intialization_Template

      - name: Terraform Intializes
        shell: pwsh
        run: |
          cd Terraform-Infrastructure
          (Get-Content ./variables.tf).Replace('replace-variable', "${{ secrets.STORAGE_ACCOUNT_NAME }}") | Set-Content ./variables.tf
          terraform init -backend-config="access_key=${{ secrets.INTIAL_STORAGE_KEY }}"  -backend-config="storage_account_name=${{ secrets.INTIAL_STORAGE_ACCOUNT }}"

      - name: Terraform Destroy
        run: |
          cd Terraform-Infrastructure
          terraform destroy --auto-approve

