name: Intial Deployment

on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/terraform-kube-workflow.yaml'
  workflow_dispatch:

jobs:
  Terraform_And_Kubernetes:

    runs-on: ubuntu-latest
    env: 
      AKS_CLUSTER_NAME: "rtpykube"
      RESOURCE_GROUP_NAME: "rt-infra"
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Intializes Terraform
        uses: hashicorp/setup-terraform@v2


      - name: KeywordReplace For Terraform 
        uses: cschleiden/replace-tokens@v1
        with: 
          files: '["Terraform-Infrastructure/variables.tf"]'
          tokenPrefix: __
          tokenSuffix: __
        env:
          AKS_CLUSTER_NAME: ${{ env.AKS_CLUSTER_NAME }}
          RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}

      - name: Powershell Script Terraform
        # working-directory: Terraform-Infrastructure/
        shell: pwsh
        run: ./Terraform-Infrastructure/run.ps1

      - name: Get latest tag
        id: latest_tag
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.1
        with:
          org: ${{ secrets.DOCKERHUB_USERNAME }}
          repo: 'review_trackers_project'

      - name: KeywordReplace For Kubernetes
        uses: cschleiden/replace-tokens@v1
        with: 
          files: '["/Kubernetes/deployment.yaml"]'
          tokenPrefix: __
          tokenSuffix: __
        env: 
          REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME}}
          IMAGE_NAME: review_trackers_project
          TAG: ${{ steps.latest_tag.outputs.tag }}

      - name: AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{  env.RESOURCE_GROUP_NAME }}
          cluster-name: ${{  env.AKS_CLUSTER_NAME }}
      


